# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the
# previous two terms. By starting with 1 and 2, the first 10 terms will
# be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

import time
start = time.time()

ans = 2
terms = [1, 2, 3]
max = 4000000

while terms[2] <= max:

    terms[0:2] = terms[1:3]
    terms[2] = sum(terms[0:2])

    if (terms[2] % 2 == 0) and (terms[2] < max):
        ans += terms[2]

end = time.time()
print("The answer to Problem 2 is: %s" % ans)
print("<< Returned in %s seconds >>" % (end - start))