# Problem 44
#
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The
# first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their
# difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum
# and difference are pentagonal and D = |Pk − Pj| is minimised; what is
# the value of D?

import eutils.seqs as seqs
import time
start = time.time()

ceil = 10000

p = [seqs.pentagon(n) for n in range(1, ceil)]
lkup = dict(zip(p, [0] * ceil))

p = [[x, y, y - x]
     for i, x in enumerate(p)
     for j, y in enumerate(p[i+1:])
     if ((y - x) in lkup) and ((y + x) in lkup)]

ans = sorted(p, key = lambda x: x[2])[0][2]

end = time.time()
print("The answer to Problem 44 is: %s" % ans)
print("<< Returned in %s seconds >>" % (end - start))