#' Problem 2
#'
#' Each new term in the Fibonacci sequence is generated by adding the
#' previous two terms. By starting with 1 and 2, the first 10 terms will
#' be:
#'
#' 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#'
#' By considering the terms in the Fibonacci sequence whose values do
#' not exceed four million, find the sum of the even-valued terms.

library(magrittr)
start <- Sys.time()

fib <- c(1, 2, 3, 5, 8, 13, 21, 34, 55, 89)

n <- fib[length(fib)] + fib[length(fib) - 1]
while (n < 4000000) {
  fib <- c(fib, n)
  n <- fib[length(fib)] + fib[length(fib) - 1]
}

ans <- sum(fib[fib %% 2 == 0])

end <- Sys.time()
paste('The answer to Problem 2 is:', ans,
      '\n<< Returned in', end - start, 'seconds >>') %>%
  cat()